version: "3.9"

services:
  rss-summarizer:
    build: .
    container_name: rss-summarizer
    volumes:
      - ./feeds.txt:/app/feeds.txt
      - ./data:/data
    command: >
      --file /app/feeds.txt
      --output /data/summaries.json
      --host localhost
      --model smollm2:135m
    environment:
      - PYTHONUNBUFFERED=1
